StringBuilderPool
oblac/jodd-util pull request #2
Opened 2020-09-27 09:40 UTC by igr

2020-09-27 12:48 UTC, slandelle requested changes
Stupid me: forgot to reset pooled StringBuilders...

2020-09-27 12:48 UTC, slandelle commented on src/main/java/jodd/util/StringBuilderPool.java
> +		return sb != null ? sb : new StringBuilder();
```suggestion
		if (sb != null) {
			sb.setLength(0);
			return sb;
		} else {
			return new StringBuilder();
		}
```

2020-09-27 12:50 UTC, slandelle requested changes

2020-09-27 12:50 UTC, slandelle commented on src/main/java/jodd/net/HtmlDecoder.java
> +					result.append(html.substring(lastIndex));
```suggestion
					result.append(html, lastIndex, len);
```

2020-09-28 13:05 UTC, igr commented
@slandelle please see my benchmark

```
StringUtil_removeBenchmark.removeNew                a  thrpt    5  29089.686 ± 222.621  ops/ms
StringUtil_removeBenchmark.removeNew               ba  thrpt    5  24278.007 ± 145.268  ops/ms
StringUtil_removeBenchmark.removeNew              cab  thrpt    5  22196.510 ± 212.803  ops/ms
StringUtil_removeBenchmark.removeNew            abcde  thrpt    5  23367.545 ± 430.193  ops/ms
StringUtil_removeBenchmark.removeNew  bcdefghaijklman  thrpt    5  17268.509 ± 163.351  ops/ms
StringUtil_removeBenchmark.removeOld                a  thrpt    5  57116.090 ± 881.963  ops/ms
StringUtil_removeBenchmark.removeOld               ba  thrpt    5  40605.504 ± 463.230  ops/ms
StringUtil_removeBenchmark.removeOld              cab  thrpt    5  40103.663 ± 609.040  ops/ms
StringUtil_removeBenchmark.removeOld            abcde  thrpt    5  35670.546 ± 535.558  ops/ms
StringUtil_removeBenchmark.removeOld  bcdefghaijklman  thrpt    5  29990.477 ± 348.026  ops/ms
```

Am i doing something wrong?

2020-09-29 07:18 UTC, slandelle commented
@igr Sadly, it looks like the new strategy is only a win for large Strings. I think you can revert latest commit.

2020-09-30 10:29 UTC, slandelle commented
@igr Maybe I wasn't clear. The StringBuilderPool is definitely a good thing. Only this commit 99ad746ecd603e87587d0e1653a9aaf07952c07d wasn't.

2020-09-30 10:40 UTC, slandelle commented
I don't own the PR, otherwise I would have remove the wrong commit.

2020-10-04 14:39 UTC, igr commented
Closing this one and opening: https://github.com/oblac/jodd-util/pull/4

2020-10-04 14:39 UTC, closed without merging